baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = ["hugo-pathways-theme", "reveal-hugo"]
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[markup.highlight]
style = "js"

[params]
  editURL = "https://coding-for-the-web.lsupathways.org/admin"
  description = "Educational material for Coding for the Web"
  author = "Tate Carson"
  showVisitedLinks = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[Languages]
[Languages.en]
title = "Educational material for Coding for the Web"
weight = 1
languageName = "English"




